/*
    ChibiOS - Copyright (C) 2006..2016 Giovanni Di Sirio
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/

/*
    Generated by gen-board.h.py based on board.yaml
*/

#ifndef _BOARD_H_
#define _BOARD_H_


/*
    Setup for Portfire
*/

/*
    Board identifier
*/
#define BOARD_PORTFIRE
#define BOARD_NAME                     "Portfire"

/*
    Ethernet related stuff
*/
#define BOARD_PHY_ID                    0x00221560
#define BOARD_PHY_RMII


/*
    Board oscillators-related settings.
*/
#if !defined(STM32_LSECLK)
#define STM32_LSECLK                   0U
#endif

#if !defined(STM32_HSECLK)
#define STM32_HSECLK                   26000000U
#endif

/*
    Board voltages
    Required for performance limits calculation.
*/
#define STM32_VDD                      330U

/*
    MCU type as defined in the ST header.
*/
#define STM32F407xx

/*
    IO pins assignments.
*/

#define GPIOA_PIN0                     0U
#define GPIOA_RMII_REF_CLK             1U
#define GPIOA_RMII_MDIO                2U
#define GPIOA_AUX_BUS_RX               3U
#define GPIOA_PIN4                     4U
#define GPIOA_PIN5                     5U
#define GPIOA_PIN6                     6U
#define GPIOA_RMII_CRS_DV              7U
#define GPIOA_CH19                     8U
#define GPIOA_CH20                     9U
#define GPIOA_CH21                     10U
#define GPIOA_PIN11                    11U
#define GPIOA_PIN12                    12U
#define GPIOA_SWDIO                    13U
#define GPIOA_SWCLK                    14U
#define GPIOA_ROM_CS                   15U

#define GPIOB_ARM                      0U
#define GPIOB_CONT                     1U
#define GPIOB_CONT_EN                  2U
#define GPIOB_CH22                     3U
#define GPIOB_CH23                     4U
#define GPIOB_CH24                     5U
#define GPIOB_CH25                     6U
#define GPIOB_CH26                     7U
#define GPIOB_CH30                     8U
#define GPIOB_CH29                     9U
#define GPIOB_CH1                      10U
#define GPIOB_RMII_TX_EN               11U
#define GPIOB_RMII_TXD0                12U
#define GPIOB_RMII_TXD1                13U
#define GPIOB_CH8                      14U
#define GPIOB_CH9                      15U

#define GPIOC_PIN0                     0U
#define GPIOC_RMII_MDC                 1U
#define GPIOC_PIN2                     2U
#define GPIOC_PIN3                     3U
#define GPIOC_RMII_RXD0                4U
#define GPIOC_RMII_RXD1                5U
#define GPIOC_CH16                     6U
#define GPIOC_CH17                     7U
#define GPIOC_CH18                     8U
#define GPIOC_PIN9                     9U
#define GPIOC_ROM_SCK                  10U
#define GPIOC_ROM_MISO                 11U
#define GPIOC_ROM_MOSI                 12U
#define GPIOC_PIN13                    13U
#define GPIOC_PIN14                    14U
#define GPIOC_PIN15                    15U

#define GPIOD_PIN0                     0U
#define GPIOD_PIN1                     1U
#define GPIOD_PIN2                     2U
#define GPIOD_PIN3                     3U
#define GPIOD_PIN4                     4U
#define GPIOD_PIN5                     5U
#define GPIOD_PIN6                     6U
#define GPIOD_PIN7                     7U
#define GPIOD_CH10                     8U
#define GPIOD_CH11                     9U
#define GPIOD_PIN10                    10U
#define GPIOD_CH12                     11U
#define GPIOD_CH13                     12U
#define GPIOD_CH14                     13U
#define GPIOD_CH15                     14U
#define GPIOD_PIN15                    15U

#define GPIOE_CH28                     0U
#define GPIOE_CH27                     1U
#define GPIOE_PIN2                     2U
#define GPIOE_PIN3                     3U
#define GPIOE_PIN4                     4U
#define GPIOE_PIN5                     5U
#define GPIOE_PIN6                     6U
#define GPIOE_STATUS                   7U
#define GPIOE_ERROR                    8U
#define GPIOE_TRAFFIC                  9U
#define GPIOE_CH7                      10U
#define GPIOE_CH6                      11U
#define GPIOE_CH5                      12U
#define GPIOE_CH4                      13U
#define GPIOE_CH3                      14U
#define GPIOE_CH2                      15U

#define GPIOF_PIN0                     0U
#define GPIOF_PIN1                     1U
#define GPIOF_PIN2                     2U
#define GPIOF_PIN3                     3U
#define GPIOF_PIN4                     4U
#define GPIOF_PIN5                     5U
#define GPIOF_PIN6                     6U
#define GPIOF_PIN7                     7U
#define GPIOF_PIN8                     8U
#define GPIOF_PIN9                     9U
#define GPIOF_PIN10                    10U
#define GPIOF_PIN11                    11U
#define GPIOF_PIN12                    12U
#define GPIOF_PIN13                    13U
#define GPIOF_PIN14                    14U
#define GPIOF_PIN15                    15U

#define GPIOG_PIN0                     0U
#define GPIOG_PIN1                     1U
#define GPIOG_PIN2                     2U
#define GPIOG_PIN3                     3U
#define GPIOG_PIN4                     4U
#define GPIOG_PIN5                     5U
#define GPIOG_PIN6                     6U
#define GPIOG_PIN7                     7U
#define GPIOG_PIN8                     8U
#define GPIOG_PIN9                     9U
#define GPIOG_PIN10                    10U
#define GPIOG_PIN11                    11U
#define GPIOG_PIN12                    12U
#define GPIOG_PIN13                    13U
#define GPIOG_PIN14                    14U
#define GPIOG_PIN15                    15U

#define GPIOH_PIN0                     0U
#define GPIOH_PIN1                     1U
#define GPIOH_PIN2                     2U
#define GPIOH_PIN3                     3U
#define GPIOH_PIN4                     4U
#define GPIOH_PIN5                     5U
#define GPIOH_PIN6                     6U
#define GPIOH_PIN7                     7U
#define GPIOH_PIN8                     8U
#define GPIOH_PIN9                     9U
#define GPIOH_PIN10                    10U
#define GPIOH_PIN11                    11U
#define GPIOH_PIN12                    12U
#define GPIOH_PIN13                    13U
#define GPIOH_PIN14                    14U
#define GPIOH_PIN15                    15U

#define GPIOI_PIN0                     0U
#define GPIOI_PIN1                     1U
#define GPIOI_PIN2                     2U
#define GPIOI_PIN3                     3U
#define GPIOI_PIN4                     4U
#define GPIOI_PIN5                     5U
#define GPIOI_PIN6                     6U
#define GPIOI_PIN7                     7U
#define GPIOI_PIN8                     8U
#define GPIOI_PIN9                     9U
#define GPIOI_PIN10                    10U
#define GPIOI_PIN11                    11U
#define GPIOI_PIN12                    12U
#define GPIOI_PIN13                    13U
#define GPIOI_PIN14                    14U
#define GPIOI_PIN15                    15U

/*
    IO lines assignments.
*/

#define LINE_ARM                       PAL_LINE(GPIOB, 0U)
#define LINE_AUX_BUS_RX                PAL_LINE(GPIOA, 3U)
#define LINE_CH1                       PAL_LINE(GPIOB, 10U)
#define LINE_CH10                      PAL_LINE(GPIOD, 8U)
#define LINE_CH11                      PAL_LINE(GPIOD, 9U)
#define LINE_CH12                      PAL_LINE(GPIOD, 11U)
#define LINE_CH13                      PAL_LINE(GPIOD, 12U)
#define LINE_CH14                      PAL_LINE(GPIOD, 13U)
#define LINE_CH15                      PAL_LINE(GPIOD, 14U)
#define LINE_CH16                      PAL_LINE(GPIOC, 6U)
#define LINE_CH17                      PAL_LINE(GPIOC, 7U)
#define LINE_CH18                      PAL_LINE(GPIOC, 8U)
#define LINE_CH19                      PAL_LINE(GPIOA, 8U)
#define LINE_CH2                       PAL_LINE(GPIOE, 15U)
#define LINE_CH20                      PAL_LINE(GPIOA, 9U)
#define LINE_CH21                      PAL_LINE(GPIOA, 10U)
#define LINE_CH22                      PAL_LINE(GPIOB, 3U)
#define LINE_CH23                      PAL_LINE(GPIOB, 4U)
#define LINE_CH24                      PAL_LINE(GPIOB, 5U)
#define LINE_CH25                      PAL_LINE(GPIOB, 6U)
#define LINE_CH26                      PAL_LINE(GPIOB, 7U)
#define LINE_CH27                      PAL_LINE(GPIOE, 1U)
#define LINE_CH28                      PAL_LINE(GPIOE, 0U)
#define LINE_CH29                      PAL_LINE(GPIOB, 9U)
#define LINE_CH3                       PAL_LINE(GPIOE, 14U)
#define LINE_CH30                      PAL_LINE(GPIOB, 8U)
#define LINE_CH4                       PAL_LINE(GPIOE, 13U)
#define LINE_CH5                       PAL_LINE(GPIOE, 12U)
#define LINE_CH6                       PAL_LINE(GPIOE, 11U)
#define LINE_CH7                       PAL_LINE(GPIOE, 10U)
#define LINE_CH8                       PAL_LINE(GPIOB, 14U)
#define LINE_CH9                       PAL_LINE(GPIOB, 15U)
#define LINE_CONT                      PAL_LINE(GPIOB, 1U)
#define LINE_CONT_EN                   PAL_LINE(GPIOB, 2U)
#define LINE_ERROR                     PAL_LINE(GPIOE, 8U)
#define LINE_RMII_CRS_DV               PAL_LINE(GPIOA, 7U)
#define LINE_RMII_MDC                  PAL_LINE(GPIOC, 1U)
#define LINE_RMII_MDIO                 PAL_LINE(GPIOA, 2U)
#define LINE_RMII_REF_CLK              PAL_LINE(GPIOA, 1U)
#define LINE_RMII_RXD0                 PAL_LINE(GPIOC, 4U)
#define LINE_RMII_RXD1                 PAL_LINE(GPIOC, 5U)
#define LINE_RMII_TXD0                 PAL_LINE(GPIOB, 12U)
#define LINE_RMII_TXD1                 PAL_LINE(GPIOB, 13U)
#define LINE_RMII_TX_EN                PAL_LINE(GPIOB, 11U)
#define LINE_ROM_CS                    PAL_LINE(GPIOA, 15U)
#define LINE_ROM_MISO                  PAL_LINE(GPIOC, 11U)
#define LINE_ROM_MOSI                  PAL_LINE(GPIOC, 12U)
#define LINE_ROM_SCK                   PAL_LINE(GPIOC, 10U)
#define LINE_STATUS                    PAL_LINE(GPIOE, 7U)
#define LINE_SWCLK                     PAL_LINE(GPIOA, 14U)
#define LINE_SWDIO                     PAL_LINE(GPIOA, 13U)
#define LINE_TRAFFIC                   PAL_LINE(GPIOE, 9U)

/*
    I/O ports initial setup, this configuration is established soon after reset
    in the initialization code.
     Please refer to the STM32 Reference Manual for details.
*/
#define PIN_MODE_INPUT(n)              (0U << ((n) * 2U))
#define PIN_MODE_OUTPUT(n)             (1U << ((n) * 2U))
#define PIN_MODE_ALTERNATE(n)          (2U << ((n) * 2U))
#define PIN_MODE_ANALOG(n)             (3U << ((n) * 2U))
#define PIN_OD_LOW(n)                  (0U << (n))
#define PIN_OD_HIGH(n)                 (1U << (n))
#define PIN_OTYPE_PUSHPULL(n)          (0U << (n))
#define PIN_OTYPE_OPENDRAIN(n)         (1U << (n))
#define PIN_OSPEED_VERYLOW(n)          (0U << ((n) * 2U))
#define PIN_OSPEED_LOW(n)              (1U << ((n) * 2U))
#define PIN_OSPEED_MEDIUM(n)           (2U << ((n) * 2U))
#define PIN_OSPEED_HIGH(n)             (3U << ((n) * 2U))
#define PIN_PUPD_FLOATING(n)           (0U << ((n) * 2U))
#define PIN_PUPD_PULLUP(n)             (1U << ((n) * 2U))
#define PIN_PUPD_PULLDOWN(n)           (2U << ((n) * 2U))
#define PIN_AFIO_AF(n, v)              ((v) << (((n) % 8U) * 4U))

/*
 *  GPIOA setup:
 *
 * PA0  - PIN0                         (unused).
 * PA1  - RMII_REF_CLK                 (af11).
 * PA2  - RMII_MDIO                    (af11).
 * PA3  - AUX_BUS_RX                   (af7).
 * PA4  - PIN4                         (unused).
 * PA5  - PIN5                         (unused).
 * PA6  - PIN6                         (unused).
 * PA7  - RMII_CRS_DV                  (af11).
 * PA8  - CH19                         (output, startlow).
 * PA9  - CH20                         (output, startlow).
 * PA10 - CH21                         (output, startlow).
 * PA11 - PIN11                        (unused).
 * PA12 - PIN12                        (unused).
 * PA13 - SWDIO                        (af0, pulldown).
 * PA14 - SWCLK                        (af0, pulldown).
 * PA15 - ROM_CS                       (output).
*/
#define VAL_GPIOA_MODER                (PIN_MODE_INPUT(GPIOA_PIN0) | \
                                        PIN_MODE_ALTERNATE(GPIOA_RMII_REF_CLK) | \
                                        PIN_MODE_ALTERNATE(GPIOA_RMII_MDIO) | \
                                        PIN_MODE_ALTERNATE(GPIOA_AUX_BUS_RX) | \
                                        PIN_MODE_INPUT(GPIOA_PIN4) | \
                                        PIN_MODE_INPUT(GPIOA_PIN5) | \
                                        PIN_MODE_INPUT(GPIOA_PIN6) | \
                                        PIN_MODE_ALTERNATE(GPIOA_RMII_CRS_DV) | \
                                        PIN_MODE_OUTPUT(GPIOA_CH19) | \
                                        PIN_MODE_OUTPUT(GPIOA_CH20) | \
                                        PIN_MODE_OUTPUT(GPIOA_CH21) | \
                                        PIN_MODE_INPUT(GPIOA_PIN11) | \
                                        PIN_MODE_INPUT(GPIOA_PIN12) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SWDIO) | \
                                        PIN_MODE_ALTERNATE(GPIOA_SWCLK) | \
                                        PIN_MODE_OUTPUT(GPIOA_ROM_CS))
#define VAL_GPIOA_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOA_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_RMII_REF_CLK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_RMII_MDIO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_AUX_BUS_RX) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_RMII_CRS_DV) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_CH19) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_CH20) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_CH21) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SWDIO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_SWCLK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOA_ROM_CS))
#define VAL_GPIOA_OSPEEDR              (PIN_OSPEED_HIGH(GPIOA_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOA_RMII_REF_CLK) | \
                                        PIN_OSPEED_HIGH(GPIOA_RMII_MDIO) | \
                                        PIN_OSPEED_HIGH(GPIOA_AUX_BUS_RX) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOA_RMII_CRS_DV) | \
                                        PIN_OSPEED_HIGH(GPIOA_CH19) | \
                                        PIN_OSPEED_HIGH(GPIOA_CH20) | \
                                        PIN_OSPEED_HIGH(GPIOA_CH21) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOA_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOA_SWDIO) | \
                                        PIN_OSPEED_HIGH(GPIOA_SWCLK) | \
                                        PIN_OSPEED_HIGH(GPIOA_ROM_CS))
#define VAL_GPIOA_PUPDR                (PIN_PUPD_PULLUP(GPIOA_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOA_RMII_REF_CLK) | \
                                        PIN_PUPD_PULLUP(GPIOA_RMII_MDIO) | \
                                        PIN_PUPD_PULLUP(GPIOA_AUX_BUS_RX) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOA_RMII_CRS_DV) | \
                                        PIN_PUPD_PULLUP(GPIOA_CH19) | \
                                        PIN_PUPD_PULLUP(GPIOA_CH20) | \
                                        PIN_PUPD_PULLUP(GPIOA_CH21) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOA_PIN12) | \
                                        PIN_PUPD_PULLDOWN(GPIOA_SWDIO) | \
                                        PIN_PUPD_PULLDOWN(GPIOA_SWCLK) | \
                                        PIN_PUPD_PULLUP(GPIOA_ROM_CS))
#define VAL_GPIOA_ODR                  (PIN_OD_HIGH(GPIOA_PIN0) | \
                                        PIN_OD_HIGH(GPIOA_RMII_REF_CLK) | \
                                        PIN_OD_HIGH(GPIOA_RMII_MDIO) | \
                                        PIN_OD_HIGH(GPIOA_AUX_BUS_RX) | \
                                        PIN_OD_HIGH(GPIOA_PIN4) | \
                                        PIN_OD_HIGH(GPIOA_PIN5) | \
                                        PIN_OD_HIGH(GPIOA_PIN6) | \
                                        PIN_OD_HIGH(GPIOA_RMII_CRS_DV) | \
                                        PIN_OD_LOW(GPIOA_CH19) | \
                                        PIN_OD_LOW(GPIOA_CH20) | \
                                        PIN_OD_LOW(GPIOA_CH21) | \
                                        PIN_OD_HIGH(GPIOA_PIN11) | \
                                        PIN_OD_HIGH(GPIOA_PIN12) | \
                                        PIN_OD_HIGH(GPIOA_SWDIO) | \
                                        PIN_OD_HIGH(GPIOA_SWCLK) | \
                                        PIN_OD_HIGH(GPIOA_ROM_CS))
#define VAL_GPIOA_AFRL                 (PIN_AFIO_AF(GPIOA_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOA_RMII_REF_CLK, 11U) | \
                                        PIN_AFIO_AF(GPIOA_RMII_MDIO, 11U) | \
                                        PIN_AFIO_AF(GPIOA_AUX_BUS_RX, 7U) | \
                                        PIN_AFIO_AF(GPIOA_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOA_RMII_CRS_DV, 11U))
#define VAL_GPIOA_AFRH                 (PIN_AFIO_AF(GPIOA_CH19, 0U) | \
                                        PIN_AFIO_AF(GPIOA_CH20, 0U) | \
                                        PIN_AFIO_AF(GPIOA_CH21, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOA_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SWDIO, 0U) | \
                                        PIN_AFIO_AF(GPIOA_SWCLK, 0U) | \
                                        PIN_AFIO_AF(GPIOA_ROM_CS, 0U))

/*
 *  GPIOB setup:
 *
 * PB0  - ARM                          (output, startlow).
 * PB1  - CONT                         (analog, floating).
 * PB2  - CONT_EN                      (output, startlow).
 * PB3  - CH22                         (output, startlow).
 * PB4  - CH23                         (output, startlow).
 * PB5  - CH24                         (output, startlow).
 * PB6  - CH25                         (output, startlow).
 * PB7  - CH26                         (output, startlow).
 * PB8  - CH30                         (output, startlow).
 * PB9  - CH29                         (output, startlow).
 * PB10 - CH1                          (output, startlow).
 * PB11 - RMII_TX_EN                   (af11).
 * PB12 - RMII_TXD0                    (af11).
 * PB13 - RMII_TXD1                    (af11).
 * PB14 - CH8                          (output, startlow).
 * PB15 - CH9                          (output, startlow).
*/
#define VAL_GPIOB_MODER                (PIN_MODE_OUTPUT(GPIOB_ARM) | \
                                        PIN_MODE_ANALOG(GPIOB_CONT) | \
                                        PIN_MODE_OUTPUT(GPIOB_CONT_EN) | \
                                        PIN_MODE_OUTPUT(GPIOB_CH22) | \
                                        PIN_MODE_OUTPUT(GPIOB_CH23) | \
                                        PIN_MODE_OUTPUT(GPIOB_CH24) | \
                                        PIN_MODE_OUTPUT(GPIOB_CH25) | \
                                        PIN_MODE_OUTPUT(GPIOB_CH26) | \
                                        PIN_MODE_OUTPUT(GPIOB_CH30) | \
                                        PIN_MODE_OUTPUT(GPIOB_CH29) | \
                                        PIN_MODE_OUTPUT(GPIOB_CH1) | \
                                        PIN_MODE_ALTERNATE(GPIOB_RMII_TX_EN) | \
                                        PIN_MODE_ALTERNATE(GPIOB_RMII_TXD0) | \
                                        PIN_MODE_ALTERNATE(GPIOB_RMII_TXD1) | \
                                        PIN_MODE_OUTPUT(GPIOB_CH8) | \
                                        PIN_MODE_OUTPUT(GPIOB_CH9))
#define VAL_GPIOB_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOB_ARM) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CONT) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CONT_EN) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CH22) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CH23) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CH24) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CH25) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CH26) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CH30) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CH29) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CH1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_RMII_TX_EN) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_RMII_TXD0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_RMII_TXD1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CH8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOB_CH9))
#define VAL_GPIOB_OSPEEDR              (PIN_OSPEED_HIGH(GPIOB_ARM) | \
                                        PIN_OSPEED_HIGH(GPIOB_CONT) | \
                                        PIN_OSPEED_HIGH(GPIOB_CONT_EN) | \
                                        PIN_OSPEED_HIGH(GPIOB_CH22) | \
                                        PIN_OSPEED_HIGH(GPIOB_CH23) | \
                                        PIN_OSPEED_HIGH(GPIOB_CH24) | \
                                        PIN_OSPEED_HIGH(GPIOB_CH25) | \
                                        PIN_OSPEED_HIGH(GPIOB_CH26) | \
                                        PIN_OSPEED_HIGH(GPIOB_CH30) | \
                                        PIN_OSPEED_HIGH(GPIOB_CH29) | \
                                        PIN_OSPEED_HIGH(GPIOB_CH1) | \
                                        PIN_OSPEED_HIGH(GPIOB_RMII_TX_EN) | \
                                        PIN_OSPEED_HIGH(GPIOB_RMII_TXD0) | \
                                        PIN_OSPEED_HIGH(GPIOB_RMII_TXD1) | \
                                        PIN_OSPEED_HIGH(GPIOB_CH8) | \
                                        PIN_OSPEED_HIGH(GPIOB_CH9))
#define VAL_GPIOB_PUPDR                (PIN_PUPD_PULLUP(GPIOB_ARM) | \
                                        PIN_PUPD_FLOATING(GPIOB_CONT) | \
                                        PIN_PUPD_PULLUP(GPIOB_CONT_EN) | \
                                        PIN_PUPD_PULLUP(GPIOB_CH22) | \
                                        PIN_PUPD_PULLUP(GPIOB_CH23) | \
                                        PIN_PUPD_PULLUP(GPIOB_CH24) | \
                                        PIN_PUPD_PULLUP(GPIOB_CH25) | \
                                        PIN_PUPD_PULLUP(GPIOB_CH26) | \
                                        PIN_PUPD_PULLUP(GPIOB_CH30) | \
                                        PIN_PUPD_PULLUP(GPIOB_CH29) | \
                                        PIN_PUPD_PULLUP(GPIOB_CH1) | \
                                        PIN_PUPD_PULLUP(GPIOB_RMII_TX_EN) | \
                                        PIN_PUPD_PULLUP(GPIOB_RMII_TXD0) | \
                                        PIN_PUPD_PULLUP(GPIOB_RMII_TXD1) | \
                                        PIN_PUPD_PULLUP(GPIOB_CH8) | \
                                        PIN_PUPD_PULLUP(GPIOB_CH9))
#define VAL_GPIOB_ODR                  (PIN_OD_LOW(GPIOB_ARM) | \
                                        PIN_OD_HIGH(GPIOB_CONT) | \
                                        PIN_OD_LOW(GPIOB_CONT_EN) | \
                                        PIN_OD_LOW(GPIOB_CH22) | \
                                        PIN_OD_LOW(GPIOB_CH23) | \
                                        PIN_OD_LOW(GPIOB_CH24) | \
                                        PIN_OD_LOW(GPIOB_CH25) | \
                                        PIN_OD_LOW(GPIOB_CH26) | \
                                        PIN_OD_LOW(GPIOB_CH30) | \
                                        PIN_OD_LOW(GPIOB_CH29) | \
                                        PIN_OD_LOW(GPIOB_CH1) | \
                                        PIN_OD_HIGH(GPIOB_RMII_TX_EN) | \
                                        PIN_OD_HIGH(GPIOB_RMII_TXD0) | \
                                        PIN_OD_HIGH(GPIOB_RMII_TXD1) | \
                                        PIN_OD_LOW(GPIOB_CH8) | \
                                        PIN_OD_LOW(GPIOB_CH9))
#define VAL_GPIOB_AFRL                 (PIN_AFIO_AF(GPIOB_ARM, 0U) | \
                                        PIN_AFIO_AF(GPIOB_CONT, 0U) | \
                                        PIN_AFIO_AF(GPIOB_CONT_EN, 0U) | \
                                        PIN_AFIO_AF(GPIOB_CH22, 0U) | \
                                        PIN_AFIO_AF(GPIOB_CH23, 0U) | \
                                        PIN_AFIO_AF(GPIOB_CH24, 0U) | \
                                        PIN_AFIO_AF(GPIOB_CH25, 0U) | \
                                        PIN_AFIO_AF(GPIOB_CH26, 0U))
#define VAL_GPIOB_AFRH                 (PIN_AFIO_AF(GPIOB_CH30, 0U) | \
                                        PIN_AFIO_AF(GPIOB_CH29, 0U) | \
                                        PIN_AFIO_AF(GPIOB_CH1, 0U) | \
                                        PIN_AFIO_AF(GPIOB_RMII_TX_EN, 11U) | \
                                        PIN_AFIO_AF(GPIOB_RMII_TXD0, 11U) | \
                                        PIN_AFIO_AF(GPIOB_RMII_TXD1, 11U) | \
                                        PIN_AFIO_AF(GPIOB_CH8, 0U) | \
                                        PIN_AFIO_AF(GPIOB_CH9, 0U))

/*
 *  GPIOC setup:
 *
 * PC0  - PIN0                         (unused).
 * PC1  - RMII_MDC                     (af11).
 * PC2  - PIN2                         (unused).
 * PC3  - PIN3                         (unused).
 * PC4  - RMII_RXD0                    (af11).
 * PC5  - RMII_RXD1                    (af11).
 * PC6  - CH16                         (output, startlow).
 * PC7  - CH17                         (output, startlow).
 * PC8  - CH18                         (output, startlow).
 * PC9  - PIN9                         (unused).
 * PC10 - ROM_SCK                      (af6).
 * PC11 - ROM_MISO                     (af6).
 * PC12 - ROM_MOSI                     (af6).
 * PC13 - PIN13                        (unused).
 * PC14 - PIN14                        (unused).
 * PC15 - PIN15                        (unused).
*/
#define VAL_GPIOC_MODER                (PIN_MODE_INPUT(GPIOC_PIN0) | \
                                        PIN_MODE_ALTERNATE(GPIOC_RMII_MDC) | \
                                        PIN_MODE_INPUT(GPIOC_PIN2) | \
                                        PIN_MODE_INPUT(GPIOC_PIN3) | \
                                        PIN_MODE_ALTERNATE(GPIOC_RMII_RXD0) | \
                                        PIN_MODE_ALTERNATE(GPIOC_RMII_RXD1) | \
                                        PIN_MODE_OUTPUT(GPIOC_CH16) | \
                                        PIN_MODE_OUTPUT(GPIOC_CH17) | \
                                        PIN_MODE_OUTPUT(GPIOC_CH18) | \
                                        PIN_MODE_INPUT(GPIOC_PIN9) | \
                                        PIN_MODE_ALTERNATE(GPIOC_ROM_SCK) | \
                                        PIN_MODE_ALTERNATE(GPIOC_ROM_MISO) | \
                                        PIN_MODE_ALTERNATE(GPIOC_ROM_MOSI) | \
                                        PIN_MODE_INPUT(GPIOC_PIN13) | \
                                        PIN_MODE_INPUT(GPIOC_PIN14) | \
                                        PIN_MODE_INPUT(GPIOC_PIN15))
#define VAL_GPIOC_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOC_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_RMII_MDC) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_RMII_RXD0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_RMII_RXD1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_CH16) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_CH17) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_CH18) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_ROM_SCK) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_ROM_MISO) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_ROM_MOSI) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOC_PIN15))
#define VAL_GPIOC_OSPEEDR              (PIN_OSPEED_HIGH(GPIOC_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOC_RMII_MDC) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOC_RMII_RXD0) | \
                                        PIN_OSPEED_HIGH(GPIOC_RMII_RXD1) | \
                                        PIN_OSPEED_HIGH(GPIOC_CH16) | \
                                        PIN_OSPEED_HIGH(GPIOC_CH17) | \
                                        PIN_OSPEED_HIGH(GPIOC_CH18) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOC_ROM_SCK) | \
                                        PIN_OSPEED_HIGH(GPIOC_ROM_MISO) | \
                                        PIN_OSPEED_HIGH(GPIOC_ROM_MOSI) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOC_PIN15))
#define VAL_GPIOC_PUPDR                (PIN_PUPD_PULLUP(GPIOC_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOC_RMII_MDC) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOC_RMII_RXD0) | \
                                        PIN_PUPD_PULLUP(GPIOC_RMII_RXD1) | \
                                        PIN_PUPD_PULLUP(GPIOC_CH16) | \
                                        PIN_PUPD_PULLUP(GPIOC_CH17) | \
                                        PIN_PUPD_PULLUP(GPIOC_CH18) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOC_ROM_SCK) | \
                                        PIN_PUPD_PULLUP(GPIOC_ROM_MISO) | \
                                        PIN_PUPD_PULLUP(GPIOC_ROM_MOSI) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOC_PIN15))
#define VAL_GPIOC_ODR                  (PIN_OD_HIGH(GPIOC_PIN0) | \
                                        PIN_OD_HIGH(GPIOC_RMII_MDC) | \
                                        PIN_OD_HIGH(GPIOC_PIN2) | \
                                        PIN_OD_HIGH(GPIOC_PIN3) | \
                                        PIN_OD_HIGH(GPIOC_RMII_RXD0) | \
                                        PIN_OD_HIGH(GPIOC_RMII_RXD1) | \
                                        PIN_OD_LOW(GPIOC_CH16) | \
                                        PIN_OD_LOW(GPIOC_CH17) | \
                                        PIN_OD_LOW(GPIOC_CH18) | \
                                        PIN_OD_HIGH(GPIOC_PIN9) | \
                                        PIN_OD_HIGH(GPIOC_ROM_SCK) | \
                                        PIN_OD_HIGH(GPIOC_ROM_MISO) | \
                                        PIN_OD_HIGH(GPIOC_ROM_MOSI) | \
                                        PIN_OD_HIGH(GPIOC_PIN13) | \
                                        PIN_OD_HIGH(GPIOC_PIN14) | \
                                        PIN_OD_HIGH(GPIOC_PIN15))
#define VAL_GPIOC_AFRL                 (PIN_AFIO_AF(GPIOC_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOC_RMII_MDC, 11U) | \
                                        PIN_AFIO_AF(GPIOC_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOC_RMII_RXD0, 11U) | \
                                        PIN_AFIO_AF(GPIOC_RMII_RXD1, 11U) | \
                                        PIN_AFIO_AF(GPIOC_CH16, 0U) | \
                                        PIN_AFIO_AF(GPIOC_CH17, 0U))
#define VAL_GPIOC_AFRH                 (PIN_AFIO_AF(GPIOC_CH18, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOC_ROM_SCK, 6U) | \
                                        PIN_AFIO_AF(GPIOC_ROM_MISO, 6U) | \
                                        PIN_AFIO_AF(GPIOC_ROM_MOSI, 6U) | \
                                        PIN_AFIO_AF(GPIOC_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOC_PIN15, 0U))

/*
 *  GPIOD setup:
 *
 * PD0  - PIN0                         (unused).
 * PD1  - PIN1                         (unused).
 * PD2  - PIN2                         (unused).
 * PD3  - PIN3                         (unused).
 * PD4  - PIN4                         (unused).
 * PD5  - PIN5                         (unused).
 * PD6  - PIN6                         (unused).
 * PD7  - PIN7                         (unused).
 * PD8  - CH10                         (output, startlow).
 * PD9  - CH11                         (output, startlow).
 * PD10 - PIN10                        (unused).
 * PD11 - CH12                         (output, startlow).
 * PD12 - CH13                         (output, startlow).
 * PD13 - CH14                         (output, startlow).
 * PD14 - CH15                         (output, startlow).
 * PD15 - PIN15                        (unused).
*/
#define VAL_GPIOD_MODER                (PIN_MODE_INPUT(GPIOD_PIN0) | \
                                        PIN_MODE_INPUT(GPIOD_PIN1) | \
                                        PIN_MODE_INPUT(GPIOD_PIN2) | \
                                        PIN_MODE_INPUT(GPIOD_PIN3) | \
                                        PIN_MODE_INPUT(GPIOD_PIN4) | \
                                        PIN_MODE_INPUT(GPIOD_PIN5) | \
                                        PIN_MODE_INPUT(GPIOD_PIN6) | \
                                        PIN_MODE_INPUT(GPIOD_PIN7) | \
                                        PIN_MODE_OUTPUT(GPIOD_CH10) | \
                                        PIN_MODE_OUTPUT(GPIOD_CH11) | \
                                        PIN_MODE_INPUT(GPIOD_PIN10) | \
                                        PIN_MODE_OUTPUT(GPIOD_CH12) | \
                                        PIN_MODE_OUTPUT(GPIOD_CH13) | \
                                        PIN_MODE_OUTPUT(GPIOD_CH14) | \
                                        PIN_MODE_OUTPUT(GPIOD_CH15) | \
                                        PIN_MODE_INPUT(GPIOD_PIN15))
#define VAL_GPIOD_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOD_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_CH10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_CH11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_CH12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_CH13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_CH14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_CH15) | \
                                        PIN_OTYPE_PUSHPULL(GPIOD_PIN15))
#define VAL_GPIOD_OSPEEDR              (PIN_OSPEED_HIGH(GPIOD_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOD_CH10) | \
                                        PIN_OSPEED_HIGH(GPIOD_CH11) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOD_CH12) | \
                                        PIN_OSPEED_HIGH(GPIOD_CH13) | \
                                        PIN_OSPEED_HIGH(GPIOD_CH14) | \
                                        PIN_OSPEED_HIGH(GPIOD_CH15) | \
                                        PIN_OSPEED_HIGH(GPIOD_PIN15))
#define VAL_GPIOD_PUPDR                (PIN_PUPD_PULLUP(GPIOD_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOD_CH10) | \
                                        PIN_PUPD_PULLUP(GPIOD_CH11) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOD_CH12) | \
                                        PIN_PUPD_PULLUP(GPIOD_CH13) | \
                                        PIN_PUPD_PULLUP(GPIOD_CH14) | \
                                        PIN_PUPD_PULLUP(GPIOD_CH15) | \
                                        PIN_PUPD_PULLUP(GPIOD_PIN15))
#define VAL_GPIOD_ODR                  (PIN_OD_HIGH(GPIOD_PIN0) | \
                                        PIN_OD_HIGH(GPIOD_PIN1) | \
                                        PIN_OD_HIGH(GPIOD_PIN2) | \
                                        PIN_OD_HIGH(GPIOD_PIN3) | \
                                        PIN_OD_HIGH(GPIOD_PIN4) | \
                                        PIN_OD_HIGH(GPIOD_PIN5) | \
                                        PIN_OD_HIGH(GPIOD_PIN6) | \
                                        PIN_OD_HIGH(GPIOD_PIN7) | \
                                        PIN_OD_LOW(GPIOD_CH10) | \
                                        PIN_OD_LOW(GPIOD_CH11) | \
                                        PIN_OD_HIGH(GPIOD_PIN10) | \
                                        PIN_OD_LOW(GPIOD_CH12) | \
                                        PIN_OD_LOW(GPIOD_CH13) | \
                                        PIN_OD_LOW(GPIOD_CH14) | \
                                        PIN_OD_LOW(GPIOD_CH15) | \
                                        PIN_OD_HIGH(GPIOD_PIN15))
#define VAL_GPIOD_AFRL                 (PIN_AFIO_AF(GPIOD_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN7, 0U))
#define VAL_GPIOD_AFRH                 (PIN_AFIO_AF(GPIOD_CH10, 0U) | \
                                        PIN_AFIO_AF(GPIOD_CH11, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOD_CH12, 0U) | \
                                        PIN_AFIO_AF(GPIOD_CH13, 0U) | \
                                        PIN_AFIO_AF(GPIOD_CH14, 0U) | \
                                        PIN_AFIO_AF(GPIOD_CH15, 0U) | \
                                        PIN_AFIO_AF(GPIOD_PIN15, 0U))

/*
 *  GPIOE setup:
 *
 * PE0  - CH28                         (output, startlow).
 * PE1  - CH27                         (output, startlow).
 * PE2  - PIN2                         (unused).
 * PE3  - PIN3                         (unused).
 * PE4  - PIN4                         (unused).
 * PE5  - PIN5                         (unused).
 * PE6  - PIN6                         (unused).
 * PE7  - STATUS                       (output, startlow).
 * PE8  - ERROR                        (output, startlow).
 * PE9  - TRAFFIC                      (output, startlow).
 * PE10 - CH7                          (output, startlow).
 * PE11 - CH6                          (output, startlow).
 * PE12 - CH5                          (output, startlow).
 * PE13 - CH4                          (output, startlow).
 * PE14 - CH3                          (output, startlow).
 * PE15 - CH2                          (output, startlow).
*/
#define VAL_GPIOE_MODER                (PIN_MODE_OUTPUT(GPIOE_CH28) | \
                                        PIN_MODE_OUTPUT(GPIOE_CH27) | \
                                        PIN_MODE_INPUT(GPIOE_PIN2) | \
                                        PIN_MODE_INPUT(GPIOE_PIN3) | \
                                        PIN_MODE_INPUT(GPIOE_PIN4) | \
                                        PIN_MODE_INPUT(GPIOE_PIN5) | \
                                        PIN_MODE_INPUT(GPIOE_PIN6) | \
                                        PIN_MODE_OUTPUT(GPIOE_STATUS) | \
                                        PIN_MODE_OUTPUT(GPIOE_ERROR) | \
                                        PIN_MODE_OUTPUT(GPIOE_TRAFFIC) | \
                                        PIN_MODE_OUTPUT(GPIOE_CH7) | \
                                        PIN_MODE_OUTPUT(GPIOE_CH6) | \
                                        PIN_MODE_OUTPUT(GPIOE_CH5) | \
                                        PIN_MODE_OUTPUT(GPIOE_CH4) | \
                                        PIN_MODE_OUTPUT(GPIOE_CH3) | \
                                        PIN_MODE_OUTPUT(GPIOE_CH2))
#define VAL_GPIOE_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOE_CH28) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_CH27) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_STATUS) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_ERROR) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_TRAFFIC) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_CH7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_CH6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_CH5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_CH4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_CH3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOE_CH2))
#define VAL_GPIOE_OSPEEDR              (PIN_OSPEED_HIGH(GPIOE_CH28) | \
                                        PIN_OSPEED_HIGH(GPIOE_CH27) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOE_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOE_STATUS) | \
                                        PIN_OSPEED_HIGH(GPIOE_ERROR) | \
                                        PIN_OSPEED_HIGH(GPIOE_TRAFFIC) | \
                                        PIN_OSPEED_HIGH(GPIOE_CH7) | \
                                        PIN_OSPEED_HIGH(GPIOE_CH6) | \
                                        PIN_OSPEED_HIGH(GPIOE_CH5) | \
                                        PIN_OSPEED_HIGH(GPIOE_CH4) | \
                                        PIN_OSPEED_HIGH(GPIOE_CH3) | \
                                        PIN_OSPEED_HIGH(GPIOE_CH2))
#define VAL_GPIOE_PUPDR                (PIN_PUPD_PULLUP(GPIOE_CH28) | \
                                        PIN_PUPD_PULLUP(GPIOE_CH27) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOE_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOE_STATUS) | \
                                        PIN_PUPD_PULLUP(GPIOE_ERROR) | \
                                        PIN_PUPD_PULLUP(GPIOE_TRAFFIC) | \
                                        PIN_PUPD_PULLUP(GPIOE_CH7) | \
                                        PIN_PUPD_PULLUP(GPIOE_CH6) | \
                                        PIN_PUPD_PULLUP(GPIOE_CH5) | \
                                        PIN_PUPD_PULLUP(GPIOE_CH4) | \
                                        PIN_PUPD_PULLUP(GPIOE_CH3) | \
                                        PIN_PUPD_PULLUP(GPIOE_CH2))
#define VAL_GPIOE_ODR                  (PIN_OD_LOW(GPIOE_CH28) | \
                                        PIN_OD_LOW(GPIOE_CH27) | \
                                        PIN_OD_HIGH(GPIOE_PIN2) | \
                                        PIN_OD_HIGH(GPIOE_PIN3) | \
                                        PIN_OD_HIGH(GPIOE_PIN4) | \
                                        PIN_OD_HIGH(GPIOE_PIN5) | \
                                        PIN_OD_HIGH(GPIOE_PIN6) | \
                                        PIN_OD_LOW(GPIOE_STATUS) | \
                                        PIN_OD_LOW(GPIOE_ERROR) | \
                                        PIN_OD_LOW(GPIOE_TRAFFIC) | \
                                        PIN_OD_LOW(GPIOE_CH7) | \
                                        PIN_OD_LOW(GPIOE_CH6) | \
                                        PIN_OD_LOW(GPIOE_CH5) | \
                                        PIN_OD_LOW(GPIOE_CH4) | \
                                        PIN_OD_LOW(GPIOE_CH3) | \
                                        PIN_OD_LOW(GPIOE_CH2))
#define VAL_GPIOE_AFRL                 (PIN_AFIO_AF(GPIOE_CH28, 0U) | \
                                        PIN_AFIO_AF(GPIOE_CH27, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOE_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOE_STATUS, 0U))
#define VAL_GPIOE_AFRH                 (PIN_AFIO_AF(GPIOE_ERROR, 0U) | \
                                        PIN_AFIO_AF(GPIOE_TRAFFIC, 0U) | \
                                        PIN_AFIO_AF(GPIOE_CH7, 0U) | \
                                        PIN_AFIO_AF(GPIOE_CH6, 0U) | \
                                        PIN_AFIO_AF(GPIOE_CH5, 0U) | \
                                        PIN_AFIO_AF(GPIOE_CH4, 0U) | \
                                        PIN_AFIO_AF(GPIOE_CH3, 0U) | \
                                        PIN_AFIO_AF(GPIOE_CH2, 0U))

/*
 *  GPIOF setup:
 *
 * PF0  - PIN0                         (unused).
 * PF1  - PIN1                         (unused).
 * PF2  - PIN2                         (unused).
 * PF3  - PIN3                         (unused).
 * PF4  - PIN4                         (unused).
 * PF5  - PIN5                         (unused).
 * PF6  - PIN6                         (unused).
 * PF7  - PIN7                         (unused).
 * PF8  - PIN8                         (unused).
 * PF9  - PIN9                         (unused).
 * PF10 - PIN10                        (unused).
 * PF11 - PIN11                        (unused).
 * PF12 - PIN12                        (unused).
 * PF13 - PIN13                        (unused).
 * PF14 - PIN14                        (unused).
 * PF15 - PIN15                        (unused).
*/
#define VAL_GPIOF_MODER                (PIN_MODE_INPUT(GPIOF_PIN0) | \
                                        PIN_MODE_INPUT(GPIOF_PIN1) | \
                                        PIN_MODE_INPUT(GPIOF_PIN2) | \
                                        PIN_MODE_INPUT(GPIOF_PIN3) | \
                                        PIN_MODE_INPUT(GPIOF_PIN4) | \
                                        PIN_MODE_INPUT(GPIOF_PIN5) | \
                                        PIN_MODE_INPUT(GPIOF_PIN6) | \
                                        PIN_MODE_INPUT(GPIOF_PIN7) | \
                                        PIN_MODE_INPUT(GPIOF_PIN8) | \
                                        PIN_MODE_INPUT(GPIOF_PIN9) | \
                                        PIN_MODE_INPUT(GPIOF_PIN10) | \
                                        PIN_MODE_INPUT(GPIOF_PIN11) | \
                                        PIN_MODE_INPUT(GPIOF_PIN12) | \
                                        PIN_MODE_INPUT(GPIOF_PIN13) | \
                                        PIN_MODE_INPUT(GPIOF_PIN14) | \
                                        PIN_MODE_INPUT(GPIOF_PIN15))
#define VAL_GPIOF_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOF_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOF_PIN15))
#define VAL_GPIOF_OSPEEDR              (PIN_OSPEED_HIGH(GPIOF_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOF_PIN15))
#define VAL_GPIOF_PUPDR                (PIN_PUPD_PULLUP(GPIOF_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOF_PIN15))
#define VAL_GPIOF_ODR                  (PIN_OD_HIGH(GPIOF_PIN0) | \
                                        PIN_OD_HIGH(GPIOF_PIN1) | \
                                        PIN_OD_HIGH(GPIOF_PIN2) | \
                                        PIN_OD_HIGH(GPIOF_PIN3) | \
                                        PIN_OD_HIGH(GPIOF_PIN4) | \
                                        PIN_OD_HIGH(GPIOF_PIN5) | \
                                        PIN_OD_HIGH(GPIOF_PIN6) | \
                                        PIN_OD_HIGH(GPIOF_PIN7) | \
                                        PIN_OD_HIGH(GPIOF_PIN8) | \
                                        PIN_OD_HIGH(GPIOF_PIN9) | \
                                        PIN_OD_HIGH(GPIOF_PIN10) | \
                                        PIN_OD_HIGH(GPIOF_PIN11) | \
                                        PIN_OD_HIGH(GPIOF_PIN12) | \
                                        PIN_OD_HIGH(GPIOF_PIN13) | \
                                        PIN_OD_HIGH(GPIOF_PIN14) | \
                                        PIN_OD_HIGH(GPIOF_PIN15))
#define VAL_GPIOF_AFRL                 (PIN_AFIO_AF(GPIOF_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN7, 0U))
#define VAL_GPIOF_AFRH                 (PIN_AFIO_AF(GPIOF_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOF_PIN15, 0U))

/*
 *  GPIOG setup:
 *
 * PG0  - PIN0                         (unused).
 * PG1  - PIN1                         (unused).
 * PG2  - PIN2                         (unused).
 * PG3  - PIN3                         (unused).
 * PG4  - PIN4                         (unused).
 * PG5  - PIN5                         (unused).
 * PG6  - PIN6                         (unused).
 * PG7  - PIN7                         (unused).
 * PG8  - PIN8                         (unused).
 * PG9  - PIN9                         (unused).
 * PG10 - PIN10                        (unused).
 * PG11 - PIN11                        (unused).
 * PG12 - PIN12                        (unused).
 * PG13 - PIN13                        (unused).
 * PG14 - PIN14                        (unused).
 * PG15 - PIN15                        (unused).
*/
#define VAL_GPIOG_MODER                (PIN_MODE_INPUT(GPIOG_PIN0) | \
                                        PIN_MODE_INPUT(GPIOG_PIN1) | \
                                        PIN_MODE_INPUT(GPIOG_PIN2) | \
                                        PIN_MODE_INPUT(GPIOG_PIN3) | \
                                        PIN_MODE_INPUT(GPIOG_PIN4) | \
                                        PIN_MODE_INPUT(GPIOG_PIN5) | \
                                        PIN_MODE_INPUT(GPIOG_PIN6) | \
                                        PIN_MODE_INPUT(GPIOG_PIN7) | \
                                        PIN_MODE_INPUT(GPIOG_PIN8) | \
                                        PIN_MODE_INPUT(GPIOG_PIN9) | \
                                        PIN_MODE_INPUT(GPIOG_PIN10) | \
                                        PIN_MODE_INPUT(GPIOG_PIN11) | \
                                        PIN_MODE_INPUT(GPIOG_PIN12) | \
                                        PIN_MODE_INPUT(GPIOG_PIN13) | \
                                        PIN_MODE_INPUT(GPIOG_PIN14) | \
                                        PIN_MODE_INPUT(GPIOG_PIN15))
#define VAL_GPIOG_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOG_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOG_PIN15))
#define VAL_GPIOG_OSPEEDR              (PIN_OSPEED_HIGH(GPIOG_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOG_PIN15))
#define VAL_GPIOG_PUPDR                (PIN_PUPD_PULLUP(GPIOG_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOG_PIN15))
#define VAL_GPIOG_ODR                  (PIN_OD_HIGH(GPIOG_PIN0) | \
                                        PIN_OD_HIGH(GPIOG_PIN1) | \
                                        PIN_OD_HIGH(GPIOG_PIN2) | \
                                        PIN_OD_HIGH(GPIOG_PIN3) | \
                                        PIN_OD_HIGH(GPIOG_PIN4) | \
                                        PIN_OD_HIGH(GPIOG_PIN5) | \
                                        PIN_OD_HIGH(GPIOG_PIN6) | \
                                        PIN_OD_HIGH(GPIOG_PIN7) | \
                                        PIN_OD_HIGH(GPIOG_PIN8) | \
                                        PIN_OD_HIGH(GPIOG_PIN9) | \
                                        PIN_OD_HIGH(GPIOG_PIN10) | \
                                        PIN_OD_HIGH(GPIOG_PIN11) | \
                                        PIN_OD_HIGH(GPIOG_PIN12) | \
                                        PIN_OD_HIGH(GPIOG_PIN13) | \
                                        PIN_OD_HIGH(GPIOG_PIN14) | \
                                        PIN_OD_HIGH(GPIOG_PIN15))
#define VAL_GPIOG_AFRL                 (PIN_AFIO_AF(GPIOG_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN7, 0U))
#define VAL_GPIOG_AFRH                 (PIN_AFIO_AF(GPIOG_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOG_PIN15, 0U))

/*
 *  GPIOH setup:
 *
 * PH0  - PIN0                         (unused).
 * PH1  - PIN1                         (unused).
 * PH2  - PIN2                         (unused).
 * PH3  - PIN3                         (unused).
 * PH4  - PIN4                         (unused).
 * PH5  - PIN5                         (unused).
 * PH6  - PIN6                         (unused).
 * PH7  - PIN7                         (unused).
 * PH8  - PIN8                         (unused).
 * PH9  - PIN9                         (unused).
 * PH10 - PIN10                        (unused).
 * PH11 - PIN11                        (unused).
 * PH12 - PIN12                        (unused).
 * PH13 - PIN13                        (unused).
 * PH14 - PIN14                        (unused).
 * PH15 - PIN15                        (unused).
*/
#define VAL_GPIOH_MODER                (PIN_MODE_INPUT(GPIOH_PIN0) | \
                                        PIN_MODE_INPUT(GPIOH_PIN1) | \
                                        PIN_MODE_INPUT(GPIOH_PIN2) | \
                                        PIN_MODE_INPUT(GPIOH_PIN3) | \
                                        PIN_MODE_INPUT(GPIOH_PIN4) | \
                                        PIN_MODE_INPUT(GPIOH_PIN5) | \
                                        PIN_MODE_INPUT(GPIOH_PIN6) | \
                                        PIN_MODE_INPUT(GPIOH_PIN7) | \
                                        PIN_MODE_INPUT(GPIOH_PIN8) | \
                                        PIN_MODE_INPUT(GPIOH_PIN9) | \
                                        PIN_MODE_INPUT(GPIOH_PIN10) | \
                                        PIN_MODE_INPUT(GPIOH_PIN11) | \
                                        PIN_MODE_INPUT(GPIOH_PIN12) | \
                                        PIN_MODE_INPUT(GPIOH_PIN13) | \
                                        PIN_MODE_INPUT(GPIOH_PIN14) | \
                                        PIN_MODE_INPUT(GPIOH_PIN15))
#define VAL_GPIOH_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOH_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOH_PIN15))
#define VAL_GPIOH_OSPEEDR              (PIN_OSPEED_HIGH(GPIOH_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOH_PIN15))
#define VAL_GPIOH_PUPDR                (PIN_PUPD_PULLUP(GPIOH_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOH_PIN15))
#define VAL_GPIOH_ODR                  (PIN_OD_HIGH(GPIOH_PIN0) | \
                                        PIN_OD_HIGH(GPIOH_PIN1) | \
                                        PIN_OD_HIGH(GPIOH_PIN2) | \
                                        PIN_OD_HIGH(GPIOH_PIN3) | \
                                        PIN_OD_HIGH(GPIOH_PIN4) | \
                                        PIN_OD_HIGH(GPIOH_PIN5) | \
                                        PIN_OD_HIGH(GPIOH_PIN6) | \
                                        PIN_OD_HIGH(GPIOH_PIN7) | \
                                        PIN_OD_HIGH(GPIOH_PIN8) | \
                                        PIN_OD_HIGH(GPIOH_PIN9) | \
                                        PIN_OD_HIGH(GPIOH_PIN10) | \
                                        PIN_OD_HIGH(GPIOH_PIN11) | \
                                        PIN_OD_HIGH(GPIOH_PIN12) | \
                                        PIN_OD_HIGH(GPIOH_PIN13) | \
                                        PIN_OD_HIGH(GPIOH_PIN14) | \
                                        PIN_OD_HIGH(GPIOH_PIN15))
#define VAL_GPIOH_AFRL                 (PIN_AFIO_AF(GPIOH_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN7, 0U))
#define VAL_GPIOH_AFRH                 (PIN_AFIO_AF(GPIOH_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOH_PIN15, 0U))

/*
 *  GPIOI setup:
 *
 * PI0  - PIN0                         (unused).
 * PI1  - PIN1                         (unused).
 * PI2  - PIN2                         (unused).
 * PI3  - PIN3                         (unused).
 * PI4  - PIN4                         (unused).
 * PI5  - PIN5                         (unused).
 * PI6  - PIN6                         (unused).
 * PI7  - PIN7                         (unused).
 * PI8  - PIN8                         (unused).
 * PI9  - PIN9                         (unused).
 * PI10 - PIN10                        (unused).
 * PI11 - PIN11                        (unused).
 * PI12 - PIN12                        (unused).
 * PI13 - PIN13                        (unused).
 * PI14 - PIN14                        (unused).
 * PI15 - PIN15                        (unused).
*/
#define VAL_GPIOI_MODER                (PIN_MODE_INPUT(GPIOI_PIN0) | \
                                        PIN_MODE_INPUT(GPIOI_PIN1) | \
                                        PIN_MODE_INPUT(GPIOI_PIN2) | \
                                        PIN_MODE_INPUT(GPIOI_PIN3) | \
                                        PIN_MODE_INPUT(GPIOI_PIN4) | \
                                        PIN_MODE_INPUT(GPIOI_PIN5) | \
                                        PIN_MODE_INPUT(GPIOI_PIN6) | \
                                        PIN_MODE_INPUT(GPIOI_PIN7) | \
                                        PIN_MODE_INPUT(GPIOI_PIN8) | \
                                        PIN_MODE_INPUT(GPIOI_PIN9) | \
                                        PIN_MODE_INPUT(GPIOI_PIN10) | \
                                        PIN_MODE_INPUT(GPIOI_PIN11) | \
                                        PIN_MODE_INPUT(GPIOI_PIN12) | \
                                        PIN_MODE_INPUT(GPIOI_PIN13) | \
                                        PIN_MODE_INPUT(GPIOI_PIN14) | \
                                        PIN_MODE_INPUT(GPIOI_PIN15))
#define VAL_GPIOI_OTYPER               (PIN_OTYPE_PUSHPULL(GPIOI_PIN0) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN1) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN2) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN3) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN4) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN5) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN6) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN7) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN8) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN9) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN10) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN11) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN12) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN13) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN14) | \
                                        PIN_OTYPE_PUSHPULL(GPIOI_PIN15))
#define VAL_GPIOI_OSPEEDR              (PIN_OSPEED_HIGH(GPIOI_PIN0) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN1) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN2) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN3) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN4) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN5) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN6) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN7) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN8) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN9) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN10) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN11) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN12) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN13) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN14) | \
                                        PIN_OSPEED_HIGH(GPIOI_PIN15))
#define VAL_GPIOI_PUPDR                (PIN_PUPD_PULLUP(GPIOI_PIN0) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN1) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN2) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN3) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN4) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN5) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN6) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN7) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN8) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN9) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN10) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN11) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN12) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN13) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN14) | \
                                        PIN_PUPD_PULLUP(GPIOI_PIN15))
#define VAL_GPIOI_ODR                  (PIN_OD_HIGH(GPIOI_PIN0) | \
                                        PIN_OD_HIGH(GPIOI_PIN1) | \
                                        PIN_OD_HIGH(GPIOI_PIN2) | \
                                        PIN_OD_HIGH(GPIOI_PIN3) | \
                                        PIN_OD_HIGH(GPIOI_PIN4) | \
                                        PIN_OD_HIGH(GPIOI_PIN5) | \
                                        PIN_OD_HIGH(GPIOI_PIN6) | \
                                        PIN_OD_HIGH(GPIOI_PIN7) | \
                                        PIN_OD_HIGH(GPIOI_PIN8) | \
                                        PIN_OD_HIGH(GPIOI_PIN9) | \
                                        PIN_OD_HIGH(GPIOI_PIN10) | \
                                        PIN_OD_HIGH(GPIOI_PIN11) | \
                                        PIN_OD_HIGH(GPIOI_PIN12) | \
                                        PIN_OD_HIGH(GPIOI_PIN13) | \
                                        PIN_OD_HIGH(GPIOI_PIN14) | \
                                        PIN_OD_HIGH(GPIOI_PIN15))
#define VAL_GPIOI_AFRL                 (PIN_AFIO_AF(GPIOI_PIN0, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN1, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN2, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN3, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN4, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN5, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN6, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN7, 0U))
#define VAL_GPIOI_AFRH                 (PIN_AFIO_AF(GPIOI_PIN8, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN9, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN10, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN11, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN12, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN13, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN14, 0U) | \
                                        PIN_AFIO_AF(GPIOI_PIN15, 0U))

#if !defined(_FROM_ASM_)
#ifdef __cplusplus
extern "C" {
#endif
  void boardInit(void);
#ifdef __cplusplus
}
#endif
#endif /* _FROM_ASM_ */

#endif /* _BOARD_H_ */
